// Madame Celandra — Rider-Waite-Smith deck data
// Images: public-domain RWS deck (1909), served from sacred-texts.com.
// If an image fails to load we fall back to a stylized SVG placeholder.

const IMG_BASE = "https://www.sacred-texts.com/tarot/pkt/img/";

const TAROT_DECK = [
  // ───────── Major Arcana ─────────
  { name: "The Fool",              suit: "major", img: IMG_BASE + "ar00.jpg",
    upright:  "new beginnings, innocence, spontaneity, a leap of faith",
    reversed: "recklessness, hesitation, risk-taking that ignores warnings" },
  { name: "The Magician",          suit: "major", img: IMG_BASE + "ar01.jpg",
    upright:  "manifestation, willpower, skill, focused intention",
    reversed: "manipulation, untapped talent, self-deception" },
  { name: "The High Priestess",    suit: "major", img: IMG_BASE + "ar02.jpg",
    upright:  "intuition, the subconscious, sacred knowledge held in silence",
    reversed: "secrets revealed, blocked intuition, superficial thinking" },
  { name: "The Empress",           suit: "major", img: IMG_BASE + "ar03.jpg",
    upright:  "femininity, abundance, nurturing, creative fertility",
    reversed: "creative block, dependence, neglect of self or others" },
  { name: "The Emperor",           suit: "major", img: IMG_BASE + "ar04.jpg",
    upright:  "authority, structure, fatherly protection, established order",
    reversed: "domination, rigidity, loss of control, tyranny" },
  { name: "The Hierophant",        suit: "major", img: IMG_BASE + "ar05.jpg",
    upright:  "tradition, spiritual guidance, conformity, shared belief",
    reversed: "rebellion, unconventional paths, questioning dogma" },
  { name: "The Lovers",            suit: "major", img: IMG_BASE + "ar06.jpg",
    upright:  "union, choice, alignment of values, harmony between opposites",
    reversed: "imbalance, indecision, misalignment, broken trust" },
  { name: "The Chariot",           suit: "major", img: IMG_BASE + "ar07.jpg",
    upright:  "determination, victory through willpower, disciplined direction",
    reversed: "lack of direction, aggression, self-doubt stalling progress" },
  { name: "Strength",              suit: "major", img: IMG_BASE + "ar08.jpg",
    upright:  "courage, inner strength, patience, compassionate power",
    reversed: "self-doubt, raw impulses, fear masquerading as weakness" },
  { name: "The Hermit",            suit: "major", img: IMG_BASE + "ar09.jpg",
    upright:  "soul-searching, introspection, inner guidance, wise solitude",
    reversed: "isolation, loneliness, withdrawal, refusing counsel" },
  { name: "Wheel of Fortune",      suit: "major", img: IMG_BASE + "ar10.jpg",
    upright:  "cycles, turning points, fortune, destiny unfolding",
    reversed: "bad luck, resistance to change, broken cycles" },
  { name: "Justice",               suit: "major", img: IMG_BASE + "ar11.jpg",
    upright:  "fairness, truth, cause and effect, accountability",
    reversed: "unfairness, dishonesty, avoiding consequences" },
  { name: "The Hanged Man",        suit: "major", img: IMG_BASE + "ar12.jpg",
    upright:  "surrender, new perspective, pause, willing sacrifice",
    reversed: "stalling, needless martyrdom, resistance, indecision" },
  { name: "Death",                 suit: "major", img: IMG_BASE + "ar13.jpg",
    upright:  "endings, transformation, letting go, profound change",
    reversed: "resistance to change, clinging, fear of transition" },
  { name: "Temperance",            suit: "major", img: IMG_BASE + "ar14.jpg",
    upright:  "balance, moderation, patient blending, alchemy of opposites",
    reversed: "imbalance, excess, self-healing needed, re-alignment" },
  { name: "The Devil",             suit: "major", img: IMG_BASE + "ar15.jpg",
    upright:  "attachment, shadow-self, addictions, self-imposed bondage",
    reversed: "breaking free, reclaiming power, awareness of chains" },
  { name: "The Tower",             suit: "major", img: IMG_BASE + "ar16.jpg",
    upright:  "sudden upheaval, revelation, the collapse of false structures",
    reversed: "averted disaster, delayed reckoning, fear of change" },
  { name: "The Star",              suit: "major", img: IMG_BASE + "ar17.jpg",
    upright:  "hope, renewal, inspiration, serenity after storm",
    reversed: "despair, loss of faith, disconnection from purpose" },
  { name: "The Moon",              suit: "major", img: IMG_BASE + "ar18.jpg",
    upright:  "illusion, intuition, the unconscious, dreamlike uncertainty",
    reversed: "clarity emerging, confusion lifting, truth from fog" },
  { name: "The Sun",               suit: "major", img: IMG_BASE + "ar19.jpg",
    upright:  "joy, success, vitality, radiant positivity",
    reversed: "temporary gloom, delayed joy, excessive optimism" },
  { name: "Judgement",             suit: "major", img: IMG_BASE + "ar20.jpg",
    upright:  "awakening, calling, inner reckoning, spiritual rebirth",
    reversed: "self-doubt, ignoring the call, lack of self-awareness" },
  { name: "The World",             suit: "major", img: IMG_BASE + "ar21.jpg",
    upright:  "completion, fulfillment, harmony, wholeness achieved",
    reversed: "loose ends, delayed closure, lack of completion" },

  // ───────── Wands (Fire — inspiration, will, creativity) ─────────
  { name: "Ace of Wands",          suit: "wands", img: IMG_BASE + "waac.jpg",
    upright:  "creative spark, new passion, inspired beginnings",
    reversed: "delays, hesitation, creative blocks" },
  { name: "Two of Wands",          suit: "wands", img: IMG_BASE + "wa02.jpg",
    upright:  "planning, making decisions, looking ahead",
    reversed: "fear of unknown, scattered plans, playing it safe" },
  { name: "Three of Wands",        suit: "wands", img: IMG_BASE + "wa03.jpg",
    upright:  "expansion, foresight, ships coming in",
    reversed: "delays, obstacles, shrinking horizons" },
  { name: "Four of Wands",         suit: "wands", img: IMG_BASE + "wa04.jpg",
    upright:  "celebration, homecoming, joyful milestones",
    reversed: "transition, lack of support, unstable foundations" },
  { name: "Five of Wands",         suit: "wands", img: IMG_BASE + "wa05.jpg",
    upright:  "conflict, competition, petty disagreements",
    reversed: "resolution, avoiding conflict, finding common ground" },
  { name: "Six of Wands",          suit: "wands", img: IMG_BASE + "wa06.jpg",
    upright:  "victory, recognition, public success",
    reversed: "fall from grace, private achievement, lack of recognition" },
  { name: "Seven of Wands",        suit: "wands", img: IMG_BASE + "wa07.jpg",
    upright:  "defiance, perseverance, standing your ground",
    reversed: "overwhelm, giving up, exhaustion" },
  { name: "Eight of Wands",        suit: "wands", img: IMG_BASE + "wa08.jpg",
    upright:  "swift action, momentum, messages arriving",
    reversed: "delays, miscommunication, frustration" },
  { name: "Nine of Wands",         suit: "wands", img: IMG_BASE + "wa09.jpg",
    upright:  "resilience, persistence, last stand",
    reversed: "burnout, paranoia, depletion" },
  { name: "Ten of Wands",          suit: "wands", img: IMG_BASE + "wa10.jpg",
    upright:  "burden, responsibility, hard-won success",
    reversed: "release, delegation, letting go of extra weight" },
  { name: "Page of Wands",         suit: "wands", img: IMG_BASE + "wapa.jpg",
    upright:  "enthusiasm, exploration, a spark of new passion",
    reversed: "setbacks, lack of direction, restless energy" },
  { name: "Knight of Wands",       suit: "wands", img: IMG_BASE + "wakn.jpg",
    upright:  "adventure, impulsiveness, passionate action",
    reversed: "recklessness, anger, volatility" },
  { name: "Queen of Wands",        suit: "wands", img: IMG_BASE + "waqu.jpg",
    upright:  "confidence, warmth, charisma, determined vision",
    reversed: "jealousy, self-doubt, demanding energy" },
  { name: "King of Wands",         suit: "wands", img: IMG_BASE + "waki.jpg",
    upright:  "leadership, vision, bold ownership",
    reversed: "impulsiveness, domineering, unrealized vision" },

  // ───────── Cups (Water — emotion, love, intuition) ─────────
  { name: "Ace of Cups",           suit: "cups", img: IMG_BASE + "cuac.jpg",
    upright:  "new feelings, overflowing heart, spiritual love",
    reversed: "emotional blockage, repressed feelings, emptied cup" },
  { name: "Two of Cups",           suit: "cups", img: IMG_BASE + "cu02.jpg",
    upright:  "partnership, mutual attraction, reciprocal love",
    reversed: "imbalance, broken trust, disconnection" },
  { name: "Three of Cups",         suit: "cups", img: IMG_BASE + "cu03.jpg",
    upright:  "celebration, friendship, chosen family",
    reversed: "isolation, gossip, social exhaustion" },
  { name: "Four of Cups",          suit: "cups", img: IMG_BASE + "cu04.jpg",
    upright:  "contemplation, apathy, missing what's offered",
    reversed: "renewed interest, awareness, acceptance" },
  { name: "Five of Cups",          suit: "cups", img: IMG_BASE + "cu05.jpg",
    upright:  "grief, regret, dwelling on loss",
    reversed: "moving on, finding what remains, forgiveness" },
  { name: "Six of Cups",           suit: "cups", img: IMG_BASE + "cu06.jpg",
    upright:  "nostalgia, childhood joy, innocence",
    reversed: "stuck in the past, outgrown patterns, moving forward" },
  { name: "Seven of Cups",         suit: "cups", img: IMG_BASE + "cu07.jpg",
    upright:  "choices, fantasy, wishful thinking",
    reversed: "clarity, focused choice, grounded priorities" },
  { name: "Eight of Cups",         suit: "cups", img: IMG_BASE + "cu08.jpg",
    upright:  "walking away, seeking meaning, disillusionment",
    reversed: "fear of change, returning, indecision" },
  { name: "Nine of Cups",          suit: "cups", img: IMG_BASE + "cu09.jpg",
    upright:  "emotional satisfaction, wishes fulfilled, contentment",
    reversed: "hollow pleasures, unmet wishes, over-indulgence" },
  { name: "Ten of Cups",           suit: "cups", img: IMG_BASE + "cu10.jpg",
    upright:  "harmonious home, emotional fulfillment, family joy",
    reversed: "domestic friction, misaligned values, broken bonds" },
  { name: "Page of Cups",          suit: "cups", img: IMG_BASE + "cupa.jpg",
    upright:  "creative messages, emotional curiosity, gentle surprises",
    reversed: "emotional immaturity, creative block, moodiness" },
  { name: "Knight of Cups",        suit: "cups", img: IMG_BASE + "cukn.jpg",
    upright:  "romance, imagination, an invitation",
    reversed: "moodiness, escapism, unrealistic ideals" },
  { name: "Queen of Cups",         suit: "cups", img: IMG_BASE + "cuqu.jpg",
    upright:  "compassion, intuition, emotional depth",
    reversed: "codependence, emotional overwhelm, insecurity" },
  { name: "King of Cups",          suit: "cups", img: IMG_BASE + "cuki.jpg",
    upright:  "emotional balance, diplomacy, wise heart",
    reversed: "manipulation, moodiness, emotional suppression" },

  // ───────── Swords (Air — thought, truth, conflict) ─────────
  { name: "Ace of Swords",         suit: "swords", img: IMG_BASE + "swac.jpg",
    upright:  "breakthrough, clarity, a cutting truth",
    reversed: "confusion, miscommunication, blunted ideas" },
  { name: "Two of Swords",         suit: "swords", img: IMG_BASE + "sw02.jpg",
    upright:  "stalemate, hard choices, willful blindness",
    reversed: "indecision lifting, truth seen, stalemate broken" },
  { name: "Three of Swords",       suit: "swords", img: IMG_BASE + "sw03.jpg",
    upright:  "heartbreak, painful truth, grief",
    reversed: "healing, releasing pain, forgiveness" },
  { name: "Four of Swords",        suit: "swords", img: IMG_BASE + "sw04.jpg",
    upright:  "rest, recovery, contemplation",
    reversed: "restlessness, burnout, premature re-entry" },
  { name: "Five of Swords",        suit: "swords", img: IMG_BASE + "sw05.jpg",
    upright:  "conflict, hollow victory, ego",
    reversed: "reconciliation, releasing resentment, compromise" },
  { name: "Six of Swords",         suit: "swords", img: IMG_BASE + "sw06.jpg",
    upright:  "transition, moving on, calmer waters ahead",
    reversed: "resistance to change, stuck, unfinished business" },
  { name: "Seven of Swords",       suit: "swords", img: IMG_BASE + "sw07.jpg",
    upright:  "deception, strategy, getting away with something",
    reversed: "confession, coming clean, return of what was taken" },
  { name: "Eight of Swords",       suit: "swords", img: IMG_BASE + "sw08.jpg",
    upright:  "self-imposed restriction, victim mindset, feeling trapped",
    reversed: "liberation, clarity of escape, taking back power" },
  { name: "Nine of Swords",        suit: "swords", img: IMG_BASE + "sw09.jpg",
    upright:  "anxiety, nightmares, fear magnified at night",
    reversed: "hope returning, fears confronted, light at dawn" },
  { name: "Ten of Swords",         suit: "swords", img: IMG_BASE + "sw10.jpg",
    upright:  "painful ending, rock bottom, finality",
    reversed: "recovery, getting back up, the worst is past" },
  { name: "Page of Swords",        suit: "swords", img: IMG_BASE + "swpa.jpg",
    upright:  "curiosity, eager learning, watchfulness",
    reversed: "gossip, scattered thoughts, careless speech" },
  { name: "Knight of Swords",      suit: "swords", img: IMG_BASE + "swkn.jpg",
    upright:  "swift action, ambition, single-minded drive",
    reversed: "recklessness, aggression, burnout" },
  { name: "Queen of Swords",       suit: "swords", img: IMG_BASE + "swqu.jpg",
    upright:  "clear boundaries, honesty, independent thought",
    reversed: "coldness, bitterness, over-critical mind" },
  { name: "King of Swords",        suit: "swords", img: IMG_BASE + "swki.jpg",
    upright:  "intellectual authority, truthful judgment, clarity",
    reversed: "abuse of power, cold calculation, dogmatism" },

  // ───────── Pentacles (Earth — body, money, the material) ─────────
  { name: "Ace of Pentacles",      suit: "pentacles", img: IMG_BASE + "peac.jpg",
    upright:  "new opportunity, prosperity, a seed of abundance",
    reversed: "missed opportunity, scarcity mindset, poor planning" },
  { name: "Two of Pentacles",      suit: "pentacles", img: IMG_BASE + "pe02.jpg",
    upright:  "juggling, adaptability, balance of priorities",
    reversed: "overwhelm, disorganization, dropped balls" },
  { name: "Three of Pentacles",    suit: "pentacles", img: IMG_BASE + "pe03.jpg",
    upright:  "collaboration, skilled craftsmanship, teamwork",
    reversed: "disharmony, lack of teamwork, mediocre work" },
  { name: "Four of Pentacles",     suit: "pentacles", img: IMG_BASE + "pe04.jpg",
    upright:  "security, saving, holding tight",
    reversed: "generosity, letting go of control, open hand" },
  { name: "Five of Pentacles",     suit: "pentacles", img: IMG_BASE + "pe05.jpg",
    upright:  "hardship, feeling left out, financial worry",
    reversed: "recovery, help arriving, end of hardship" },
  { name: "Six of Pentacles",      suit: "pentacles", img: IMG_BASE + "pe06.jpg",
    upright:  "generosity, fair exchange, giving and receiving",
    reversed: "strings attached, imbalance in giving, debts" },
  { name: "Seven of Pentacles",    suit: "pentacles", img: IMG_BASE + "pe07.jpg",
    upright:  "patient cultivation, long-term vision, assessment",
    reversed: "impatience, wasted effort, wrong strategy" },
  { name: "Eight of Pentacles",    suit: "pentacles", img: IMG_BASE + "pe08.jpg",
    upright:  "diligent practice, mastery, skill-building",
    reversed: "shortcuts, lack of focus, uninspired work" },
  { name: "Nine of Pentacles",     suit: "pentacles", img: IMG_BASE + "pe09.jpg",
    upright:  "self-sufficiency, luxury, earned independence",
    reversed: "overspending, reliance on others, hollow wealth" },
  { name: "Ten of Pentacles",      suit: "pentacles", img: IMG_BASE + "pe10.jpg",
    upright:  "legacy, generational wealth, long-term security",
    reversed: "financial loss, family conflict, instability" },
  { name: "Page of Pentacles",     suit: "pentacles", img: IMG_BASE + "pepa.jpg",
    upright:  "new ventures, study, tangible opportunities",
    reversed: "laziness, missed opportunity, lack of planning" },
  { name: "Knight of Pentacles",   suit: "pentacles", img: IMG_BASE + "pekn.jpg",
    upright:  "diligence, routine, reliable progress",
    reversed: "stagnation, boredom, stuck in a rut" },
  { name: "Queen of Pentacles",    suit: "pentacles", img: IMG_BASE + "pequ.jpg",
    upright:  "nurturing, abundance, grounded care",
    reversed: "self-neglect, smothering, financial stress" },
  { name: "King of Pentacles",     suit: "pentacles", img: IMG_BASE + "peki.jpg",
    upright:  "wealth, stability, seasoned mastery",
    reversed: "greed, materialism, financial missteps" }
];

// Expose globally for the browser
window.TAROT_DECK = TAROT_DECK;
